### 
POST http://localhost:3000/booking/new
Content-Type: application/json

{ "booking": {
    "status": "Disponible",
    "checkIn": "2023-05-03",
    "checkOut": "2023-05-18",
    "totalPrice": 123450,
    "owner": "64ed2c49f642fa68a08f2bd4",
    "guest": "64fcfe88e2b0ebef1862e040",
    "property": "6525cf50e1427dc911b0f1dd"}
}

###
GET http://localhost:3000/booking

###
POST http://localhost:3000/booking/checkAvailability
Content-Type: application/json

{
    "checkInExp": "2023-04-03",
    "checkOutExp": "2023-05-01",
    "property": "6525cf50e1427dc911b0f1dd"
}