### 
POST http://localhost:3000/booking/new
Content-Type: application/json

{ "booking": {
    "status": "Disponible",
    "checkIn": "2023-05-03",
    "checkOut": "2023-05-18",
    "totalPrice": 123450,
    "owner": "652609400790c96f82b4cd32",
    "guest": "64fcfe88e2b0ebef1862e040",
    "property": "65260c090790c96f82b4cd7d"}
}

###
GET http://localhost:3000/booking

###
POST http://localhost:3000/booking/checkAvailability
Content-Type: application/json

{
    "booking" : {
    "checkInExp": "2023-05-19",
    "checkOutExp": "2023-05-19",
    "propertyId": "6525cf50e1427dc911b0f1dd"}
}

###
GET http://localhost:3000/booking/ownerlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWQyYzQ5ZjY0MmZhNjhhMDhmMmJkNCIsInByb3BlcnRpZXMiOlsiNjRmNjg0YmI2ZTFmZjU4M2YyYzVmM2I4IiwiNjRmNjg0YmI2ZTFmZjU4M2YyYzVmM2I4IiwiNjRmNjg0YmI2ZTFmZjU4M2YyYzVmM2I4IiwiNjRmNjg1NjJlNTMwODczYTQ3NzA0MWUxIiwiNjUyNWM0ODUwZjA0MzQzMGU3ZWIzYTFlIiwiNjUyNWNhYTRlMTczNzYxNzQ5NTFhYzdhIiwiNjUyNWNmNTBlMTQyN2RjOTExYjBmMWRkIiwiNjUyNWQwZmJjZWI2YmI5OGQ5MjYxYTlhIl0sImlhdCI6MTY5ODk2NDk0NSwiZXhwIjoxNjk4OTY2NzQ1fQ.5QswFa6KJH59kovP5MFqbBh0Q7Bqd861dR0QwokTwzE
