###
GET http://localhost:3000/city

###
POST http://localhost:3000/city/new
Content-Type: application/json

{
    "city": "Rosario",
    "provinceId": "651b444b0293a42cee704cff"
}

###
DELETE http://localhost:3000/city/delete/651b6031feffd971806bc230