###
GET http://localhost:3000

###
GET http://localhost:3000/property

###
GET http://localhost:3000/property/64ed21809160d3753831adea

###
GET http://localhost:3000/property/64ed21809160d3753831adea/user